CREATE TABLE users
(
    id         VARCHAR(100) PRIMARY KEY,
    nim        VARCHAR(100) UNIQUE NOT NULL,
    name       VARCHAR(100)        NOT NULL,
    email      VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

)